### ISSUE TITLE
Abrupt size change

### ISSUE THREAD

**Issue by DorianHawkmoon** [MaturuturuStudios/Drop#1]
When grow up, the desired behaviour is growing up until it doesn't fit and truncate the actual size.

When the previous size and the new size has a high difference (1 to 8, for example), sometimes the final size calculated is not the biggest size that fit, but one unit less. Even not growing up at all in special situations like having a ball at the side of the character, but that situation is more less usual.

We must keep in mind this point when designing the levels.

**Comment by DorianHawkmoon** [comment]
Must review the code, I didn't take care of some calculations and seems like it's the guilty one.

**Comment by IgnacioAstorga** [comment]
All is right now, closing this issue.
