### ISSUE TITLE
SendFlying bug?

### ISSUE THREAD

**Issue by DorianHawkmoon** [MaturuturuStudios/Drop#10]
Siguiendo la sugerencia de usar SendFlying cuando escupo las gotas sobrantes (método SpitDrop), cambio estas líneas:
`newDrop.GetComponent<CharacterControllerCustomPlayer>().Stop();
        newDrop.GetComponent<CharacterControllerCustom>()
           .AddForce(spitDirection*impulseSpit*Mathf.Sqrt(numberDropsRemain), ForceMode.VelocityChange);`

por estas otras, que mirando en el método, sigue siendo lo mismo:
`CharacterControllerCustom newDropController = newDrop.GetComponent<CharacterControllerCustom>();
newDropController.SendFlying(spitDirection * impulseSpit * Mathf.Sqrt(numberDropsRemain), false);`

Pero el comportamiento no es ni parecido, el impulso es mucho más fuerte e introduce un bug que es que lanza la gota, la cual choca con la pared, y cuando cae al suelo, se sigue moviendo. He mirado la pila de parámetros y parece estar bien, no sé de donde puede venir el fallo.

Los pasos para reproducirlo, además de moverse a la rama creada para testear el bug (fixing-bug, commit e3eb881d96d24f919c2020c473458cb267717453), es:
- una gota tamaño 4 en el hueco de la derecha.
- dejar caer una gota de tamaño 1 en la gota grande.

Ya lo había mencionado en el issue #6 pero parece que es un bug distinto, de hecho, ahora pasa siempre, no como antes que era aleatorio.

**Comment by IgnacioAstorga** [comment]
Explicación:
- Al usar SendFlying, el personaje disparado deja de poder moverse, lo cual significa que NO hay fricción en el aire. Esto hace que el personaje llegue potencialmente más lejos.
- El parámetro opcional booleano de SendFlying (que tu has puesto a false) indica si el personaje debería volver a la normalidad al colisionar. Tu le has dicho que no lo haga, así que normal que siga moviéndose incluso tras colisionar.

**Comment by DorianHawkmoon** [comment]
Sin fricción entonces tiene sentido que vaya más lejos, probaré a ver si ajusto entonces el valor.

Y ese es el tercer parámetro, el segundo es si tener en cuenta  la masa o no, por lo que está a true. Aparte, dicho parámetro lo estás guardando en _stopFlyingWhenHit que al parecer no estás usando en ningún sitio cuando traté de buscarlo.

**Comment by IgnacioAstorga** [comment]
Ups, cierto, no funcionaba bien ese atributo. Ya está arreglado. Si que es verdad que el primer boolean es para la masa. Esta a false por defecto, no hace falta especificarlo, pero bueno, en cualquier caso no tiene nada que ver con el problema. Le echaré un ojo más detenido.

**Comment by IgnacioAstorga** [comment]
Corregido. El problema era del CCCP al intentar hacer que un personaje se mantuviese pegado a una pared, que sobreescribía su input. Si el personaje no estaba recibiendo input (aka, no estaba siendo controlado), este se mantenía y acababa dando problemas.
