### ISSUE TITLE
Pérdida del control tras varios disparos

### ISSUE THREAD

**Issue by IgnacioAstorga** [MaturuturuStudios/Drop#4]
Hay algún caso en el que al disparar una gota se pierde el control de la misma. Parece ser que se queda atascada en modo disparo pero no puedo asegurarlo. Estos son los pasos a seguir para replicar el problema:
1. Según empieza, crecer a tamaño 2 y disparar una gota a cierta distancia.
2. Con la gota disparada, crecer a tamaño 2 y disparar a la gota original, haciéndola crecer.
3. Con la gota original, ahora de tamaño 2, disparar a la otra gota.

Según mi experiencia, esta serie de pasos provoca el bug. Ahora el jugador pierde el control de la segunda gota. Puede alternar entre el control de una y otra, pero la segunda sencillamente no se mueve.

No se si es bug de Roberto o de Toni, pero solo me deja poner uno como asignado.

Saludos.

**Comment by tonilsz** [comment]
Ok, me estaba esperando porque cuando hice el independent controller aun faltavan cosas por retocar de la fusion y  del disparo. No he tocado nada desde el jueves pasado, ya se que hay bugs, pero si los otros scrips no llaman al mio crrectamente, no puedo avanzar. En cuanto termine las 4 pijadas que me quedan de la camara, me pongo con ello. Intentad no ir buscando los errores en el codigo de los demas y dejad vuestro codigo bien. Repito, ya se que tiene errores. Aun así gracias por informar de como reproducir el bug.

**Comment by IgnacioAstorga** [comment]
Ya vi que Roberto aún no tiene el disparo refinado, fue confusión mía. En cualquier caso, dejo el issue abierto para cerrarlo cuando este completo.

**Comment by DorianHawkmoon** [comment]
Pues al final no tiene nada que ver el disparo en sí, es un problema entre la fusión y el control, porque en fusión trata de destruir una gota y establecer la otra gota como controlada, pero si no existía ya en la lista, independentControl no lo pone como controlado y como la primera queda destruida, adiós muy buenas!  

[Este es el issue](https://github.com/MaturuturuStudios/Drop/issues/5) que abrí sin ver que al final es el mismo. Por tanto, voy a cerrar este issue. Si arreglado el otro, persiste este bug, se abre de nuevo.
