### ISSUE TITLE
Strange uncontrolled drop behaviour

### ISSUE THREAD

**Issue by DorianHawkmoon** [MaturuturuStudios/Drop#6]
Step to see the bug.
Change drop when you are on a wind tube. The drop on wind will move to any direction like if we are moving it with the joystick. Same happens sometimes when spit a drop.

**Comment by IgnacioAstorga** [comment]
It should be fixed now. The problem was that the character was considered on a slope when colliding with a roof, causing it to slide among it and be able to somehow "roof jump". Check it and close the issue if it's fixed.
