### ISSUE TITLE
Destroy current drop

### ISSUE THREAD

**Issue by IgnacioAstorga** [MaturuturuStudios/Drop#8]
The method KillDrop from GameControllerIndependentControl doesn't work as expected if the drop you want to destroy is the one under control. I would advise that this method should change control to the next drop if the drop being destroyed is the one under control.

If the destroyed drop is the last one remaining, it should still destroy it. It's OK if further instructions throw exceptions, it wouldn't be a problem of the KillDrop method but of the one who destroyed the last drop.

Also, please, rename KillDrop to DestroyDrop (in order to keep consistence with CreateDrop).

**Comment by tonilsz** [comment]
I think that it is solved, check it please

**Comment by IgnacioAstorga** [comment]
Ok, it's working as expected. Thanks!
